Models/ErrorViewModel.cs
namespace TaskManager.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserTask.cs
namespace TaskManager.Models
{
    public class UserTask
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }

        public UserTask()
        {

        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Models;

namespace TaskManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskManager.Data;
using TaskManager.Models;

namespace TaskManager.Controllers
{
    public class UserTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserTasksController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserTask.ToListAsync());
        }
        
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        public async Task<IActionResult> ShowSearchResults(string searchPhrase)
        {
            return View("Index", await _context.UserTask.Where(userTask => userTask.TaskName.Contains(searchPhrase)).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            
            var userTask = await _context.UserTask.FirstOrDefaultAsync(m => m.Id == id);

            if (userTask == null) return NotFound();
            
            return View(userTask);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TaskName,TaskDescription")] UserTask userTask)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userTask);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();            

            var userTask = await _context.UserTask.FindAsync(id);

            if (userTask == null) return NotFound();
            
            return View(userTask);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TaskName,TaskDescription")] UserTask userTask)
        {
            if (id != userTask.Id) return NotFound();            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {                    
                    if (!TaskExists(userTask.Id)) return NotFound();
                    else throw;
                }

                return RedirectToAction(nameof(Index));
            }
            return View(userTask);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();            

            var userTask = await _context.UserTask.FirstOrDefaultAsync(m => m.Id == id);

            if (userTask == null) return NotFound();            

            return View(userTask);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _context.UserTask.FindAsync(id);

            if (task != null) _context.UserTask.Remove(task);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int providedId)
        {
            return _context.UserTask.Any(task => task.Id == providedId);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Task Manager</h1>
    <p>An application to keep track, create, edit or delete your own tasks.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Task Manager - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="container navbar navbar-expand-sm navbar-toggleable-sm">            
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-substack text-info-emphasis"></i>
                    <span>Task Manager</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <i class="bi bi-list"></i>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                                               
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="UserTasks" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="UserTasks" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>            
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/UserTasks/Create.cshtml
@model TaskManager.Models.UserTask

@{
    ViewData["Title"] = "Create new task";
}

<h4>Create new task</h4>
<hr />

<div class="row">
    <div>
        <a asp-action="Index">
            <i class="bi bi-arrow-left-square-fill back-arrow"></i>
        </a>
    </div>
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="TaskName" class="control-label mb-1">Title</label>
                <input asp-for="TaskName" class="form-control" />
                <span asp-validation-for="TaskName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TaskDescription" class="control-label mb-1">Description</label>
                <input asp-for="TaskDescription" class="form-control" />
                <span asp-validation-for="TaskDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>        
    </div>
    
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserTasks/Delete.cshtml
@model TaskManager.Models.UserTask

@{
    ViewData["Title"] = "Delete task";
}


<div>
    <h4>Delete task</h4>
    <hr />
    <div>
        <a asp-action="Index">
            <i class="bi bi-arrow-left-square-fill back-arrow"></i>
        </a>
    </div>
    <dl class="row">
        <dt class="col-sm-2">Task name</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.TaskName)</dd>
        <dt class="col-sm-2">Task description</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.TaskDescription)</dd>
    </dl>
    
    <h6>Are you sure you want to delete this task? This action cannot be reversed.</h6>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />       
    </form>
</div>

Views/UserTasks/Details.cshtml
@model TaskManager.Models.UserTask

@{
    ViewData["Title"] = "Task details";
}

<div>
    <h4>Task Details</h4>
    <hr />
    <div>
        <a asp-action="Index">
            <i class="bi bi-arrow-left-square-fill back-arrow"></i>
        </a>
    </div>
    <dl class="row">
        <dt class = "col-sm-2">Task name</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.TaskName)</dd>
        <dt class = "col-sm-2">Task description</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.TaskDescription)</dd>
    </dl>
</div>

Views/UserTasks/Edit.cshtml
@model TaskManager.Models.UserTask

@{
    ViewData["Title"] = "Edit task";
}

<h4>Edit task</h4>
<hr />
<div class="row">
    <div>
        <a asp-action="Index">
            <i class="bi bi-arrow-left-square-fill back-arrow"></i>
        </a>
    </div>
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group mb-2">
                <label asp-for="TaskName" class="control-label mb-1">Title</label>
                <input asp-for="TaskName" class="form-control" />
                <span asp-validation-for="TaskName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TaskDescription" class="control-label mb-1">Description</label>
                <input asp-for="TaskDescription" class="form-control" />
                <span asp-validation-for="TaskDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserTasks/Index.cshtml
@model IEnumerable<TaskManager.Models.UserTask>

@{
    ViewData["Title"] = "User tasks";
}

<p>
    <a asp-action="Create" class="addNewTask">
        <i class="bi bi-patch-plus-fill"></i>
        <span>New Task</span>
    </a>
</p>
<div class="col-6">
    <table class="table">
    <thead>
        <tr>
            <th>Task name</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaskName)
            </td>         
            <td class="taskOptions">
                    <a asp-action="Details" asp-route-id="@item.Id" class="taskDetails">
                        <i class="bi bi-info-circle"></i>                        
                    </a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="editTask">
                        <i class="bi bi-pencil-fill"></i>                        
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="deleteTask">
                        <i class="bi bi-trash-fill"></i>                        
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Views/UserTasks/ShowSearchForm.cshtml
@{
    ViewData["Title"] = "Search tasks";
}

<h4>Search for a task</h4>
<hr />
<div class="row">
    <div>
        <a asp-action="Index">
            <i class="bi bi-arrow-left-square-fill back-arrow"></i>
        </a>
    </div>
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">            
            <div class="form-group mb-3">
                <label for="SearchPhrase" class="control-label mb-1">Insert your search term</label>
                <input name="SearchPhrase" class="form-control" />                
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>